keeponpause=no
deadzonesize=0.75
osc_on_start=both
screenshot_button=yes
screenshot_mbtn_left_command=osd-msg screenshot video
vidscale=no
scalewindowed=1.2
scalefullscreen=1.2
title=${filename}
persistent_progress=yes
persistent_progress_height=20
persistent_buffer=yes
