#!/usr/bin/env bash

# https://github.com/QwenLM/qwen-code/releases/latest
QWEN_VER=0.21

if [[ ! -d ./.qwen ]]; then
    mkdir -pv ./.qwen
fi

CMD=
if [[ "$1" != "" ]]; then
    CMD="qwen $@"
fi
docker run \
    --rm -it \
    --user $(id -u):$(id -g) \
    -e HOME=$HOME \
    --tmpfs "$HOME:uid=$(id -u),gid=$(id -g),exec" \
    -v "$HOME/.qwen:$HOME/.qwen" \
    -v "$HOME/.skills:$HOME/.skills" \
    -v .:$(pwd) \
    -w $(pwd) \
    -v /var/cache/apt/archives \
    -v /var/lib/apt/lists \
    --pull always \
    ghcr.io/qwenlm/qwen-code:$QWEN_VER $CMD
