#!/usr/bin/env bash

# https://github.com/QwenLM/qwen-code/releases/latest
QWEN_VER=0.22

if [[ ! -d ./.qwen ]]; then
    mkdir -pv ./.qwen
fi

CMD=
if [[ "$1" != "" ]]; then
    CMD="qwen $@"
fi

TMPFS_MOUNT="--tmpfs $HOME:uid=$(id -u),gid=$(id -g),exec"
QWEN_MOUNT="-v $HOME/.qwen:$HOME/.qwen"
SKILLS_MOUNT="-v $HOME/.skills:$HOME/.skills"
if [[ "$(pwd)" -ef "$HOME" ]]; then
    TMPFS_MOUNT= # pwd bind already covers HOME
elif [[ "$(pwd)" -ef "$HOME/.qwen" ]]; then
    QWEN_MOUNT= # pwd bind already covers .qwen
elif [[ "$(pwd)" -ef "$HOME/.skills" ]]; then
    SKILLS_MOUNT= # pwd bind already covers .skills
fi

docker run \
    --rm -it \
    --user $(id -u):$(id -g) \
    -e HOME=$HOME \
    $TMPFS_MOUNT \
    $QWEN_MOUNT \
    $SKILLS_MOUNT \
    -v .:$(pwd) \
    -w $(pwd) \
    -v /var/cache/apt/archives \
    -v /var/lib/apt/lists \
    --pull always \
    ghcr.io/qwenlm/qwen-code:$QWEN_VER $CMD
