#!/usr/bin/env bash

# https://github.com/QwenLM/qwen-code/releases/latest
QWEN_VER=0.21

if [[ ! -d ./.qwen ]]; then
    mkdir -pv ./.qwen
fi

CMD=
if [[ "$1" != "" ]]; then
    CMD="qwen $@"
fi
docker run \
    --rm -it \
    -v "$HOME/.qwen:/root/.qwen" \
    -v "$HOME/.skills:$HOME/.skills" \
    -v .:$(pwd) \
    -w $(pwd) \
    --pull always \
    ghcr.io/qwenlm/qwen-code:$QWEN_VER $CMD
